### ISSUE TITLE
URL was not changed as per the language 

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/wp-multilang#100]
Ref ticket:- https://magazine3.in/conversation/300845?folder_id=21

Description:-
When the user tried to change the language, the menu URL was not changed as per the present language.

Screenshot:-
https://monosnap.com/direct/uNhzOYpHEUwDss9ZC66nWCXCjyhFkU

**Comment by Sanjeevsetu** [comment]
Related #25
