### ISSUE TITLE
ACF link field not working

### ISSUE THREAD

**Issue by evgeniy-vashchuk** [ahmedkaludi/wp-multilang#101]
In ACF the plugin does not translate the link type of field. It just overrides the previous language, so both languages always have the same values. Link is an essential and popular field, is it possible to make it work? This may be a reason to give up this plugin.

**Comment by Sanjeevsetu** [comment]
Hi @evgeniy-vashchuk 

Sorry for late reply. Could you please provide us some screenshots or short video of the issue ?

**Comment by evgeniy-vashchuk** [comment]
I have replaced this plugin with another one at the current moment, but I will reproduce it for you some of these days and will give you a screenshot (because I like your plugin for its simplicity and convenience).

**Comment by Sanjeevsetu** [comment]
Hi @evgeniy-vashchuk 

Thanks for the compliment. We will be more happy whenever You come back and start using our plugin. I am closing this ticket You can contact us here https://wp-multilang.com/contact-us/
