### ISSUE TITLE
A Fatal error is occurring on the user end after the update 2.4.11

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/wp-multilang#109]
A Fatal error is occurring on the user end after the update 2.4.11

Ref ticket: https://magazine3.in/conversation/311728?folder_id=27

Error: E_ERROR uppstod på rad 39 i följande fil: wp-content/plugins/wp-multilang/includes/wpm-formatting-functions.php. Felorsak: Uncaught TypeError: Argument 2 passed to wpm_array_merge_recursive() must be of the type array, null given, called in wp-content/plugins/wp-multilang/includes/integrations/class-wpm-woocommerce.php on line 197 and defined in 
 wp-content/plugins/wp-multilang/includes/wpm-formatting-functions.php:39
Stack trace:
#0 wp-content/plugins/wp-multilang/includes/integrations/class-wpm-woocommerce.php(197): wpm_array_merge_recursive(Array, NULL)
#1 httpdocs/wp-includes/class-wp-hook.php(308): WPM\Includes\Integrations\WPM_WooCommerce->add_attribute_taxonomies(NULL)
#2 /wp-includes/plugin.php(205): WP_Hook->apply_filters(NULL, Array)
#3 /httpdocs/wp-content/plugins/wp-multilang/includes/wpm-config-functions.php(53): apply_filters('wpm_taxonomies_...', NULL)
#4 httpdocs/wp-content/plugins/wp-multilang/i

**Comment by netzkundig** [comment]
We had the same issue with the Woocommerce Integration after updating to 2.4.11. Reverting back to 2.4.10 solved it for now.

**Comment by krambriw** [comment]
Yes, reverting back to 2.4.10 works. One single error report might be coincidence, two or more reports, most likely a bug in the plugin

**Comment by antaconte** [comment]
I removed the common plugin in the smallest site and got the same error.  I removed the others but not wp-multilang, same effect.
Then I reinstalled 2.4.10 and it works nice again.

I checked yesterday 2.4.12 with the same result.

Perhaps it comes from php 8.3.1 modules.  All the 7 other wordpress sites on the same server not using wp-multilang work fine .

If there is not any security issue, I can continue with 2.4.10

**Comment by antaconte** [comment]
Sorry if it's split in 3 comments.

The Apache specific error after trying to see an admin page ( ignoring the warnings ) is :

PHP Fatal error:  Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array,  null given in /www/wp-content/plugins/wp-multilang/includes/admin/class-wpm-admin-assets.php:122

Stack trace:
#0 /www/wp-content/plugins/wp-multilang/includes/admin/class-wpm-admin-assets.php(122): in_array('profile', NULL, true)
#1 /www/wp-includes/class-wp-hook.php(324): WPM\\Includes\\Admin\\WPM_Admin_Assets->admin_scripts('profile.php')
#2 /www/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#3 /www/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /www/wp-admin/admin-header.php(118): do_action('admin_enqueue_s...', 'profile.php')
#5 /www/wp-admin/user-edit.php(201): require_once('/home/0/u/www.u...')
#6 /www/wp-admin/profile.php(18): require_once('/home/0/u/www.u...')
#7 {main}
thrown in /www/wp-content/plugins/wp-multilang/includes/admin/class-wpm-admin-assets.php on line 122

The plugin list of this site is the shortest of the 3:
wp-multilang
akismet
child-theme-configurator
contact-form-7
contact-form-7-image-captcha
flamingo
cookie-law-info
duplicate-page
insert-php-code-snippet
menu-duplicator
menu-items-visibility-control
mj-update-history
to-top

But none was the  issue, checked as told above.

I checked now with a reduced php ( no memcached, no sql-lite, etc ) configuration. Same results.

Thank you for your help

**Comment by Sanjeevsetu** [comment]
Hi Everyone. 

We have just fixed this issue and have committed code here. Can anyone test it with current development branch https://github.com/ahmedkaludi/wp-multilang/tree/2.4.13 and know us whether it has fixed or not ?

**Comment by antaconte** [comment]
Hello,

the problem is solved , the admin page works again.
Thank you

**Comment by Sanjeevsetu** [comment]
Hi @antaconte 

Thanks for the confirmation.

**Comment by krambriw** [comment]
Late to the party...I could only install & test when the new version was available in the WooCommerce plugin manager
Confirming ver 2.4.13 installs & works fine!
Thanks a lot for your effort!

**Comment by Sanjeevsetu** [comment]
Thanks everyone here for the confirmation. I have closed the ticket.
