### ISSUE TITLE
Admin Pages Langauge tag disappered

### ISSUE THREAD

**Issue by 3tosh** [ahmedkaludi/wp-multilang#114]
when logged in Wordpress admin, My langauge switchers nav has been not show in  pages, posts etc.

how can i switch the langauges. 
Help Me ASAP
<img width="1186" alt="スクリーンショット 2024-09-26 20 11 07" src="https://github.com/user-attachments/assets/11054038-9bb8-4de7-8ae1-ff79be89d66a">

**Comment by Sanjeevsetu** [comment]
Hi @3tosh 

By default it should appear on pages. Have you added languages in WP-Multilang settings page?? Can you share some more details of settings ?

**Comment by 3tosh** [comment]
Hi @Sanjeevsetu 

Thank you for the response,
The problem was solved but i don't know how it solved.

[Work details]
i have deactivated and installed plugin for many times  but it was not working
at the end, i removed all the files from FTP and re installed from beginning one by one steps
and it was working.

but still not working on 「Smart custom fields」
In, 「wpm-config.json」i have added 
    "post_types": {
        "news": {},
        "member": {},
        "achievement": {}
    },
    
    ACF worked properly, but SCF is still not working.
    If you have any idea let me know.
    
    Thank you

**Comment by Sanjeevsetu** [comment]
Hi @3tosh 

I am glad to know that It has started working for you.

Regarding "Smart custom fields". WP Multilang – Translation and Multilingual Plugin is yet to be compatible with it. I have created a ticket and It will be added soon in coming updates.

Ref: https://github.com/ahmedkaludi/wp-multilang/issues/116
