### ISSUE TITLE
the new update still not work for ACF PRO

### ISSUE THREAD

**Issue by hanyewebuser** [ahmedkaludi/wp-multilang#12]
text field is work ok, but image field is not word.

The field values atr the same in all languages

**Comment by Sanjeevsetu** [comment]
There are issues with the ACF Pro plugin on user end, as settings are not being saved and ACF field values are just not updating when switching between languages.

Ref ticket : https://magazine3.in/conversation/248337?folder_id=29

**Comment by Sanjeevsetu** [comment]
Hi @hanyewebuser 

Thanks for the report. We will check it properly and fix it soon.

**Comment by Sdaud1950** [comment]
Ref  ticket; https://magazine3.in/conversation/250062?folder_id=29
