### ISSUE TITLE
Issue with Translating Titles, Subtitles, and Excerpts into Multiple Languages

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/wp-multilang#120]
Issue with Translating Titles, Subtitles, and Excerpts into Multiple Languages

Ref Ticket : https://magazine3.in/conversation/316571?folder_id=29

**Comment by shridhamdeveloper** [comment]
This issue is already referred in #78

**Comment by shridhamdeveloper** [comment]
This issue is already referred in #78

**Comment by shridhamdeveloper** [comment]
This issue is already referred in #78
