### ISSUE TITLE
Make a feature to translate slug for 2nd level of hierarchy of urls

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/wp-multilang#121]
Ref ticket: https://magazine3.in/conversation/300845?folder_id=21

Description:
We need to create a feature that works for the second level of the hierarchy in the URL. When we create a child page and assign it a parent page, the URL doesn't work and shows a 404 error.

**Comment by shridhamdeveloper** [comment]
https://github.com/ahmedkaludi/wp-multilang-pro/commit/f856e4762a1a131fd15dc39bec915045ab132039
