### ISSUE TITLE
Language Switcher not show in Menu

### ISSUE THREAD

**Issue by dimitrievski5** [ahmedkaludi/wp-multilang#123]
Hi,

After update, language switcher is not showing in menu.

Wordpress version 6.6.2
WP-Multilang version 2.4.13
PHP version PHP 8.2

**Comment by Sanjeevsetu** [comment]
Hi @dimitrievski5 

Could you please contact our support for better understanding of the issues ? Link : https://wp-multilang.com/contact-us/
