### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/wp-multilang#125]
fatal error

Uncaught Error: Call to undefined function WPM\Includes\wpm_get_language() in /home//public_html/wp-content/plugins/wp-multilang-pro/includes/class-wpm-slug-translation.php:335
Stack trace: 

Ref ticket : https://magazine3.in/conversation/301492?folder_id=29

**Comment by shridhamdeveloper** [comment]
https://github.com/ahmedkaludi/wp-multilang-pro/commit/7b546e94b0eaea319a60f12a1bf63832446166ae
