### ISSUE TITLE
Active className for active language

### ISSUE THREAD

**Issue by bystrzan** [ahmedkaludi/wp-multilang#129]
I want to hide the current language and it's simply by CSS in frontend, but editor always show ugly list without a chance to style (block uses block api version 3 so it's iframe). It could be option in block options to hide the current language, but class on li element would be quick to make and grate for developers also.

**Comment by Sanjeevsetu** [comment]
Hi @bystrzan 

Thanks for using our plugin. Could you please contact us through support for better understanding of requirement. Link: https://wp-multilang.com/contact-us/
