### ISSUE TITLE
Language switcher is missing in the widgets block editor

### ISSUE THREAD

**Issue by g4rf** [ahmedkaludi/wp-multilang#15]
If the widgets are styled via the block editor, the language switcher is missing. Like in the issue #14 the language switcher should be added via a block editor API.

As a workaround, it's possible to deactivate the block editor on widgets via 
```php
add_filter( 'use_widgets_block_editor', '__return_false' );
```
But this should be an option in the WP Multilang admin menu, not a general behaviour, as it may be unexpected to the user and broke existing widget areas.

**Comment by Sanjeevsetu** [comment]
We have added it in our last update v 2.4.5. You can now see language switcher in widgets block. Please check and let us know

**Comment by g4rf** [comment]
Thank you very much for inserting the language switcher. As you can see here, it's cutted on overflow, maybe because the "Top Toolbar" is activated. **In PR #51 is a css solution that works.**

![grafik](https://github.com/ahmedkaludi/wp-multilang/assets/18557074/2ad65ac2-6bc4-426d-8cb4-3867d4a4bc6d)
