### ISSUE TITLE
 slugs is not supported .

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/wp-multilang#25]
Need to provide support for the slug in different languages.

Ref ticket : https://magazine3.in/conversation/248337?folder_id=29

**Comment by poljansekniko** [comment]
The idea here is to offer possibility to translate slug for different types like posts, pages, taxonomies, etc. A few examples would be:

- page (regular page, front page, woocommerce pages (shop, checkout, categories...), etc.)
- posts
- blog posts
- product_cat (woocommerce)
- product (woocommerce)
- custom taxonomy

**Comment by MohammedAkramU7** [comment]
Another user : https://magazine3.in/conversation/273195?folder_id=3

**Comment by Sdaud1950** [comment]
https://magazine3.in/conversation/301492?folder_id=29

**Comment by Sdaud1950** [comment]
https://magazine3.in/conversation/304069?folder_id=29

**Comment by besiders** [comment]
Any idea when this will be completed ? Need the ability to translate the URLS.. I was told this would be completed soon.
Please let me know

**Comment by bagaweb** [comment]
> Any idea when this will be completed ? Need the ability to translate the URLS.. I was told this would be completed soon. Please let me know

I'm waiting for this feature as well.

**Comment by shridhamdeveloper** [comment]
https://github.com/ahmedkaludi/wp-multilang/commit/e18aa0d4d2a2ef356b799586cb5ddef25d47650d
https://github.com/ahmedkaludi/wp-multilang/commit/e18aa0d4d2a2ef356b799586cb5ddef25d47650d
https://github.com/ahmedkaludi/wp-multilang-pro/commit/1b608bd0621319d28ea35161d0fe4af22137dc7b
https://github.com/ahmedkaludi/wp-multilang-pro/commit/69c1e40be04094864951f770a120e7cc66e0d877
https://github.com/ahmedkaludi/wp-multilang-pro/commit/1baf7cf94a6c7a905b927e4a74837ebb26e19010

**Comment by poljansekniko** [comment]
Hey Sanjeev,

Can I get the premium version so I can test it and see if there is still
anything that can be improved?

Thanks,
Niko

**Comment by bagaweb** [comment]
Thanks @Sanjeevsetu I hoped that the slug feature would also be available for the free version.
Anyway if there's a way to test the premium version, I'll be happy to help @poljansekniko.

**Comment by Sanjeevsetu** [comment]
Hi everyone,

Kindly contact our support https://wp-multilang.com/contact-us/
