### ISSUE TITLE
Need to make a compatibility with Elementor

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/wp-multilang#26]
Ref ticket: https://magazine3.in/conversation/251590?folder_id=21

Description:-
When we added the text with the help of the editor in Elementor and tried to change the language, it wasn't working.

Here is the issue video:
https://monosnap.com/direct/fAV9cqXgpR16VDclsMd0gN8U1oKzQB

**Comment by askcode21** [comment]
Same concern: https://wordpress.org/support/topic/elementor-page-builder-13/  || https://wordpress.org/support/topic/elementor-219/
