### ISSUE TITLE
Multilanguage pages are not added to sitemap.xml

### ISSUE THREAD

**Issue by donsafo1** [ahmedkaludi/wp-multilang#27]
Multilanguage pages are not added to any sitemap.xml, checked all the most popular plugins. Only the default language is added, and the rest of the languages are not. How can I make them add automatically? It is very important.

Example:

I have default language - ukrainian, and 2 additional languages - english and russian. Only ukrainian language is in sitemap - https://onnews.com.ua/sitemap.xml (posts)
I can add in additional-sitemap by my hands, but it isn't automatically and and very time-consuming. 

It would be good if pages of all types were automatically added to the sitemap: main, category, page, tag...

**Comment by MohammedAkramU7** [comment]
Another user:- https://magazine3.in/conversation/254345?folder_id=21
