### ISSUE TITLE
WP GraphQL support

### ISSUE THREAD

**Issue by EagleEyeElite** [ahmedkaludi/wp-multilang#44]
Hey, I am currently building a website from scratch.

I am using WordPress as a CMS. And GraphQL as a glue between the frontend and the CMS.

I also wanna support multilingual. I don't like the Polylang Plugin.

Is there a way, to add GraphQL support for this plugin?

If you could give me some Ideas, to add some PHP functions myself, this would be helpful as well.

I like the work you are doing. Keep it up

Best Regards,
Conrad

**Comment by Sanjeevsetu** [comment]
Hi @EagleEyeElite 

We currently do not have any support/compatibility with GraphQL. We will add it in coming updates.

**Comment by Van-Halen** [comment]
You can use `https://yourdomain.com/graphql?lang=en`
