### ISSUE TITLE
The excerpts are not translated in the frontend Query Loop block

### ISSUE THREAD

**Issue by g4rf** [ahmedkaludi/wp-multilang#52]
There seems to be a bug with the **Excerpts** block in the **Query Loop** block in the frontend, where the excerpts are not translated. Surprisingly it works in the Gutenberg editor in the backend.

![grafik](https://github.com/ahmedkaludi/wp-multilang/assets/18557074/0beb47cf-3db5-4fb8-9353-8dcdc9ed00ff)

There is a fix for this, where we hook into `get_the_excerpt` very early to solve this problem. The very early approach should be okay, as every other plugin should await translated strings.
```php
add_filter( 'get_the_excerpt', 'wpm_translate_string', 5);
```
I added the change to the  PR #51 to solve this problem.

**Comment by Sanjeevsetu** [comment]
Hi @g4rf 

Thanks for the PR. We have merged it
