### ISSUE TITLE
Donation button still valid?

### ISSUE THREAD

**Issue by Max-Stirner** [ahmedkaludi/wp-multilang#60]
Please sorry about my bad English.

I saw that the updates of this fabulous plugin have started again and would like to donate. On the plugin page on Wordpress.org if I click on the PayPal donation button the name of the previous developer comes up. I would like to know whether this is right, or whether I should donate to the person who is now actively involved in the project.

**Comment by Sanjeevsetu** [comment]
Hi @Max-Stirner 

Thank you so much for the love you have shown to our WP-Multilang plugin. We highly appreciate it. 

We are very soon going to release a premium version of this plugin. For more info you can check out here https://wp-multilang.com/.

Regarding donation: You can use this link https://paypal.me/kaludi
