### ISSUE TITLE
WP Multilang conflicts with the Newsletter plugin.

### ISSUE THREAD

**Issue by askcode21** [ahmedkaludi/wp-multilang#61]
One user reported an issue with our WP Multilang conflicting with the Newsletter plugin. When a new user tries to subscribe, it gives an error when both plugins are used together.

Newsletter plugin: https://wordpress.org/plugins/newsletter/

Reference ticket: https://wordpress.org/support/topic/plugin-causes-problems-with-other-plugins/

**Comment by Sanjeevsetu** [comment]
this solution raised new issue so I am re-opening it
