### ISSUE TITLE
Need an option to change URL according to switcher language. 

### ISSUE THREAD

**Issue by askcode21** [ahmedkaludi/wp-multilang#62]
One user reached out to us regarding a concern about having different URLs for different languages. They described the issue as follows:

"**In one language, the URL changes appropriately. For example, my link is https://anabolenking.com/en/product/maximum-cutting-treatment-package/ in English. However, when I switch to Dutch, it should appear as https://anabolenking.com/product/kuurpakket-maximaal-cutten/. Yet, when I change the link in one language, it automatically alters both, resulting in URLs like:

https://anabolenking.com/en/product/kuurpakket-maximaal-cutten
/https://anabolenking.com/product/kuurpakket-maximaal-cutten/"****"

Reference ticket: https://wordpress.org/support/topic/links-are-not-translating/

**Comment by 77naveenop** [comment]
Another user -: https://magazine3.in/conversation/265986?folder_id=3

**Comment by Sanjeevsetu** [comment]
Related #25
