### ISSUE TITLE
The date format in “zh_CN” (simplified Chinese) does not work properly.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/wp-multilang#64]
The date format in “zh_CN” (simplified Chinese) does not work properly.

Ref Ticket :https://magazine3.in/conversation/264957?folder_id=29

**Comment by Sanjeevsetu** [comment]
The issue does not seem to valid. It is working fine at our end. Need more data to solve the issue. I am closing the ticket for now.

**Comment by chiawei-lu** [comment]
what should I do?

**Comment by Sanjeevsetu** [comment]
Hi @chiawei-lu 

Extremely sorry for it. I accidentally closed this ticket. I am re-opeing it and will fix it in next milestone for sure. Please bear with us a little longer. 

Thank you so much.

**Comment by Sanjeevsetu** [comment]
We have thoroughly tested and found that this issue might be related to WordPress core. We have raised a ticket on wp.org.

Ref: https://core.trac.wordpress.org/ticket/62428

**Comment by chiawei-lu** [comment]
Thank you!! I appreciate your help.
