### ISSUE TITLE
Call to undefined function

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/wp-multilang#65]
Ref ticket: https://magazine3.in/conversation/266201?folder_id=21

Description:-
undefined function in wp-multilang, here is the path: WPM\Includes\Integrations\is_product_category()

**Comment by zentavr** [comment]
Is it a workaround for that?

**Comment by zentavr** [comment]
Temporary removed the function `is_product_category()` invocation in 2 places:
```
./wp-content/plugins/wp-multilang/includes/integrations/class-wpm-yoast-seo.php:558:		}else if(is_archive() || is_product_category()){
./wp-content/plugins/wp-multilang/includes/integrations/class-wpm-yoast-seo.php:589:		}else if(is_archive() || is_product_category()){
```

**Comment by Sanjeevsetu** [comment]
it has been pushed in 2.4.7
