### ISSUE TITLE
Need to make a compatibility with Divi

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/wp-multilang#72]
Ref ticket: https://magazine3.in/conversation/270800?folder_id=21

Description:-
We need to make it compatible with Divi

**Comment by shridhamdeveloper** [comment]
Divi Compatibility code in pro plugin
https://github.com/ahmedkaludi/wp-multilang-pro/commit/a9f1648c8f6cc4a8cd40f3e1897113de932cab22
