### ISSUE TITLE
Need to create a feature of Automatic translation.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/wp-multilang#77]
Need to create a feature of Automatic translation.

Ref Ticket : https://magazine3.in/conversation/276409?folder_id=29

**Comment by Sdaud1950** [comment]
https://magazine3.in/conversation/300630?folder_id=29

**Comment by MohammedAkramU7** [comment]
another user: https://magazine3.in/conversation/302051?folder_id=21

**Comment by Sanjeevsetu** [comment]
It has been pushed in 2.4.11
