### ISSUE TITLE
Disable / Uninstall without remain [:en][:] tags

### ISSUE THREAD

**Issue by peterjozsefkiss** [ahmedkaludi/wp-multilang#87]
Hi,

Any advise to disable / uninstall correctly if i dont want that on main language the language tags? like [:en][:] 

Thank you!

**Comment by Sanjeevsetu** [comment]
Hi @peterjozsefkiss 

I am closing the ticket. If You still have any issues, kindly contact us or create new ticket with more details.

**Comment by peterjozsefkiss** [comment]
Hi!
Thank you for answers! I was able to do it. Only some woocommerce attributes remain what needed correct.
Thank you!
