### ISSUE TITLE
Language switcher disappears too early in Wordpress 6.6

### ISSUE THREAD

**Issue by saddy001** [ahmedkaludi/wp-multilang#91]
I updated to Wordpress 6.6 today and the language switcher dropdown disappears too early when hovering it. My theme is Twenty Twenty-Four Version 1.2.. 

Here is a video showing the effect:

https://github.com/user-attachments/assets/1551ffa6-075d-4b60-9fb8-8d2be9df3090

**Comment by Sanjeevsetu** [comment]
Hi @saddy001 

Sure, We check it.

**Comment by shridhamdeveloper** [comment]
Hi @saddy001

Please confirm whether you are using shortcode to use the language switcher.

**Comment by saddy001** [comment]
Yes, I'm using

`wpm_language_switcher('dropdown');`

from PHP. As there are some HTML problems in the code, I'm also trimming it:

`preg_replace('/\s*\R\s*/', ' ', trim($lang_switch));`

**Comment by Sanjeevsetu** [comment]
Hi @saddy001 

We have committed a fix here. Could you just try and let us know whether it fixes your issue or not ?

**Comment by saddy001** [comment]
Sure, but how can I try it?

**Comment by Sanjeevsetu** [comment]
@saddy001 

You can download zip from current development branch https://github.com/ahmedkaludi/wp-multilang/tree/2.4.13
