### ISSUE TITLE
W3TC is not removing minified files from source

### ISSUE THREAD

**Issue by saddy001** [ahmedkaludi/wp-multilang#98]
wp-multilang suffers from the same issue as WPML: 

W3TC is not removing minified files from source, if another language than the default language is selected.

https://wpml.org/errata/w3tc-is-not-minifying-files/

**Comment by Sanjeevsetu** [comment]
Hi @saddy001 

Thanks for reporting the bug. We will look at it and let you know once it is done.

**Comment by shridhamdeveloper** [comment]
Hi @saddy001

Kindly help us with some screenshots or videos to recreate this issue.

**Comment by shridhamdeveloper** [comment]
Hi @saddy001

Waiting for your reply, kindly help us here

**Comment by Sanjeevsetu** [comment]
Hi @saddy001 

We waited here and we need your help to fix this issue. Kindly contact our support https://wp-multilang.com/contact-us/. I am closing this ticket.
